name: xai_model_explanation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - notebook
  - jupyterlab
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - altair
  - pytorch >= 1.8
  - torchvision >= 0.9
  - tensorboard >= 2.0
  - opencv
  - lime
  - tensorflow
  - torch
  - os
  - skimage
